### ISSUE TITLE
Running the monitor externally

### ISSUE THREAD

**Issue by JamesHinshelwood** [ethereum/sourcify#1098]
It makes sense that Sourcify is conservative with the chains that are monitored, because of resource limitations and costs.

It would be nice if third parties could run the monitor for other chains themselves. In theory, if the monitor interacts with the Sourcify server via the normal public API, this should work and not require any trust of the parties running the monitor.

Has anyone explored this mode of operation before? How does the communication between the monitor and server work currently?

**Comment by kuzdogan** [comment]
Hi Thanks for the heads up and sorry for the late answer.

Currently, the monitor and server are modules that run together because the monitor verifies contracts through the `VerificationService` 
https://github.com/ethereum/sourcify/blob/96ba3588e346ce72d85ad14fea61a7b2c90650fb/src/monitor/monitor.ts#L285-L286
But you are totally right. This really doesn't need to be part of the server and should just tell the Sourcify server which contract to verify with the files. So this can be a totally separate module/app from the server and IMO it should be.

**Comment by marcocastignoli** [comment]
I totally agree 👍

**Comment by kuzdogan** [comment]
Created this tracker issue for this https://github.com/ethereum/sourcify/issues/1153. Closing
