### ISSUE TITLE
Embed the Swagger UI inside docs page instead of linking

### ISSUE THREAD

**Issue by kuzdogan** [ethereum/sourcify#1127]
https://docs.estuary.tech/Reference/SwaggerUI

**Comment by fernandomg** [comment]
Hey @kuzdogan, I tackled this since it seemed like the only 'good first issue' available.. The PR: https://github.com/sourcifyeth/docs/pull/20.

I swapped out the paragraphs with links to swagger.

But, it might be a smarter move to organize the API into a folder and split the Swagger and Create2 sections into separate documents.

Let me know what you think and I'll do the required changes.
