### ISSUE TITLE
[Milestone] Remix "Verifier" Plugin

### ISSUE THREAD

**Issue by kuzdogan** [ethereum/sourcify#1331]
The goal is to write a plugin that will be a "Verifier" plugin instead of separate "Sourcify" and "Etherscan" etc. plugins and present it to the Remix team. With that, the users will be able to verify their contracts in multiple places in parallel e.g. verify both on Etherscan and Sourcify simultaneously. The plugin should also be built in a modular way to support further integrations in the future.

```[tasklist]
### Tasks
- [ ] https://github.com/ethereum/sourcify/issues/1332
```

**Comment by manuelwedler** [comment]
The plugin was implemented and a first iteration of feedback integrated. The next steps are:

1. Gather last round of feedback. 
2. In the best case, Remix team likes it and we can go ahead, otherwise implement feedback.
3. Find out if we should add it as native module and how this can be done.
4. PR against Remix repo.

**Comment by kuzdogan** [comment]
Released with https://github.com/ethereum/remix-project/issues/4604
