### ISSUE TITLE
Update url handling in SourcifyDatabase to support SourcifyDB-only and SourcifyDB+repov2 configurations

### ISSUE THREAD

**Issue by marcocastignoli** [ethereum/sourcify#1640]
Currently, the [`getTree()` function](https://github.com/ethereum/sourcify/blob/6156037dde2374260830fd832b6f9831d16bf1fe/services/server/src/server/services/storageServices/SourcifyDatabaseService.ts#L416-L428) retrieves the file tree from `repositoryV1`, which forces you to run RepositoryV1Service (+ an http server) together with SourcifyDatabase. This prevents running sourcify with SourcifyDatabaseService alone or in combination with `RepositoryV2Service`.

In the current implementation, URLs are constructed using `repositoryV1.serverUrl`. We should directly use the `https://sourcify.dev/server/repository/contracts/{full_match | partial_match}/{chain}/{address}/{filePath}` API for URL construction.

**Comment by kuzdogan** [comment]
Ah ok, I thought we were reading the literal file tree from `repositoryV1` like `tree -L 2 /Users/kuzdogan/sourcify/repositoryV1/contracts/full_match/1/0x025030BdAa159f281cAe63873E68313a703725A5` and that's why I preferred not working on this now.

If we are using that for the URLs only and it's a simple fix, we can do this after #1637

**Comment by marcocastignoli** [comment]
Fixed with #1677
