### ISSUE TITLE
Verifying duplicate contracts 

### ISSUE THREAD

**Issue by kuzdogan** [ethereum/sourcify#1643]
Now that we have a database of raw bytecodes to source codes matchings we can start to verify duplicate contracts we receive automatically without even compiling.

Say we verified a GnosisSafeProxy on 0xabcd on Mainnet (1) **perfectly**. Next time someone asks us to verify the same GnosisSafeProxy contract, we first look at the onchain bytecodes of this contract. 

I was going to say we do a search with the hash but there's an issue: We don't save the onchain bytecodes as is but we save them normalized, right? So if we hash the onchain bytecode and look for it on the `code` table, we won't find anything. I guess instead we have to do a similarity search between the full onchain bytecode vs the full bytecodes in the database? 

Maybe we don't normalize or is there another way to find existing exact matches?

**Comment by marcocastignoli** [comment]
I'm not a Data Scientist, but after doing some research I think that the best way to implement bytecode similarity is the following:
- Use an [embedding model](https://www.pinecone.io/learn/vector-embeddings/) to convert bytecodes into vector representations
- Store the generated embeddings in a vector database like Pinecone
- Perform [similarity searches](https://www.pinecone.io/learn/what-is-similarity-search/) using the vector database query functionality

I think this is a very interesting experiment that we can do. Also, offering such a vector database to the community at no cost is a significant contribution.

**Comment by marcocastignoli** [comment]
**Providing additional context on how we store bytecodes and why searching for duplicates is challenging.**

There are two types of EVM bytecodes: runtime and creation. [Read more about the difference here.](https://docs.sourcify.dev/blog/talk-about-onchain-metadata-hash/#runtime-code-vs-creation-code) Ideally, we want to implement duplicate detection for both.

Focusing on runtime bytecode: the compiler outputs runtime bytecode with all libraries and immutables set to placeholders (typically 0s). In our database, runtime bytecodes are stored in this normalized form, with placeholders for all immutables and libraries—a process we call _bytecode normalization_. Additionally, bytecodes include an auxdata field, which is a fingerprint of the sources and compilation settings. You can read more about it [here](https://playground.sourcify.dev/), under the "What is Metadata" section. Unlike the rest of the bytecode, the auxdata field is not normalized.

For example (Note: this is a fictional example, highlighted fields are for illustration purposes):

608060405234801561001057600080fd5b5061012f806100206000396000f3fe6080604052348015600f57600080fd5b506004361060325760003560e01c80632e**0000000000000000(lib)00000000000000000**fd5b603d6069565b6040516048919060c2565b60405180910390f35b6067600480360381019060639190608f565b6072565b005b60008054905090565b8060008190555050565b60008135905060898160e5565b92915050565b60006020828403121560a057600080fd5b600060ac84828501607c565b91505092915050565b60bc8160db565b82525050565b600060208201905060d5600083018460b5565b92915050565b6000819050919050565b60ec8160db565b811460f657600080fd5b5**000000000000000(immutable)00000000000000000**3d8adc295c3046b**a5142c60(auxdata field)eef171f330c51c38f1498964736f6c63430008040033**


When we receive a new contract for verification, our inputs are: chain, address, files, and compilation settings.

Currently, our process is as follows:
1. Receive a contract.
2. Recompile the contract.
3. Compare the recompiled bytecode with the on-chain bytecode.
4. If they match, store the contract as verified.

Our goal is to modify this process as follows:
1. Receive a contract for verification.
2. Instead of recompiling, search our database to see if a contract with a similar bytecode already exists. Note that the only information we have before recompiling is the on-chain runtime bytecode, which we fetch using an RPC, which is not normalized.
3. After we found a similar bytecode, we apply the normalization already applied to the found similar bytecode to the on-chain bytecode, if the on-chain bytecode is exactly the same as the found bytecode after normalization we have a match that we can store skipping compilation.

The challenge with step 2 is that the on-chain bytecode is not normalized, and without recompiling, we don't know its immutables and libraries positions in the bytecode so searching for similar bytecodes is not an easy task.

**Comment by kuzdogan** [comment]
Two comments: 

- "the compiler outputs runtime bytecode with all libraries and immutables set to placeholders (typically 0s)" this is not necessarily true for linked libraries ie. if the compiler does the linking (`"libraries"` in std-json or `--libraries`) the library addresses are already filled in the compiler output runtime bytecode.

- "After we found a similar bytecode, we apply the normalization already applied to the found similar bytecode to the on-chain bytecode" This part needs more precision and elaboration to me
  1. How do we apply the "normalization already applied to the found similar bytecode"? We have the raw normalized bytecode from the `code` table. How do we know which parts of the code were normalized? Do we search for `0000`s? Do we need to find the transformations applied and 'reverse-transform' them?
  2. Imagine we see and verify a contract for the first time, how do we store the contract bytecodes in the `code` table, in terms of normalization?
    a. onchain runtime bytecode (`contracts.runtime_code_hash`): immutables, libraries, and callProtection set to `0000` and saved as such in `code`?
    b. onchain creation bytecode (`contracts.creation_code_hash`): libraries set to `0000` and saved in `code`?
    c. recompiled runtime bytecode (`compiled_contracts_runtime_code_hash`): immutables, libraries, and callProtection set to `0000` and saved as such in `code`?
    d. recompiled creation bytecode (`compiled_contracts_creation_code_hash`): libraries set to `0000` and saved in `code`?

A good point of reference and ideation can be the existing Blockscout DB and Search mechanism: https://docs.blockscout.com/about/features/ethereum-bytecode-database-microservice Here they split the bytecode into **Main** and **Metadata** parts and perform the search on only the **Main** parts. However this again begs the question how you split the Main-Metadata of an unstructured onchain bytecode. We can ask them about their exact search algorithm. (Side note: EOF solves this question)

**Comment by marcocastignoli** [comment]
I'll reply first to your second question because I don't think [this comment](https://github.com/ethereum/sourcify/issues/1643#issuecomment-2388812867) was fully understood

> A good point of reference and ideation can be the existing Blockscout DB and Search mechanism: https://docs.blockscout.com/about/features/ethereum-bytecode-database-microservice 

I think this mechanism is not optimized because when you search for a bytecode you search for bytecodes that have exactly  the same libraries / immutables, the only optimization that Blockscout does is removing the auxdata bytes.

If we use a vector database we can actually search for similar bytecodes even without normalizing the onchain bytecode used as query filter. Of course it depends a lot on how much we optimize the bytecode vectorization, but I think we can do well.

> After we found a similar bytecode, we apply the normalization already applied to the found similar bytecode to the on-chain bytecode" This part needs more precision and elaboration to me

"Do we need to find the transformations applied and 'reverse-transform' them?" My idea is to:
1. use the verifying-onchain-bytecode to search for all similar bytecodes
2. for each one of them find their transformations in the verified_contracts table (joining with compiled_contracts)
3. apply each transformation to the verifying-onchain-bytecode until we find an exact match with one of the similar bytecodes

**Comment by kuzdogan** [comment]
The vector DB is clear to me and I like that idea. I'm just exploring the Blockscout option. Don't they mark immutables and libraries as **Meta**? That's weird. Maybe with that we don't even need vectorization and that could be simpler? We don't find similar bytecodes but exact bytecodes that have their **Main** parts matching but with different **Meta**.

> apply each transformation to the verifying-onchain-bytecode until we find an exact match

You don't need to find a matching transformation, do you? The important thing is you find the sections in the bytecode that are not opcodes (i.e. like **Meta** above), and those parts match exactly. Then it can have any transformations. These transformations will be saved in the `verified_contracts` regardless if it's an "exact match with one of the similar bytecodes" or not.

**Comment by marcocastignoli** [comment]
> Don't they mark immutables and libraries as Meta? That's weird. Maybe with that we don't even need vectorization and that could be simpler?

The problem with this is that we don't know in advance the position of immutables / libraries / auxdata in the onchain_runtime_bytecode before recompiling. At the beginning we start with just the files,compilation_settings,address,chain and onchain bytecode fetched via RPC. That's why I want first to find similar bytecodes and then trying to find a match by normalizing (by applying the transformations of the found bytecodes) the **Main** part.

**Comment by rimrakhimov** [comment]
I'm going to talk a little bit about how we handle look up of similar contracts in eth-bytecode-db in blockscout.

First of all, we do not consider neither libraries nor immutables as Meta right now. In most cases that is not a problem for us because libraries usually are linked during the compilation and are not normalized anyway, and immutables changes only runtime bytecode, while most of the automatic verification occurs via creation code (we cannot, though, automatically detect similar contracts for contracts with only runtime code - e.g., genesis ones - with immutables).

To ignore cbor-encoded auxdata during the search, we split all compiled bytecodes on Main and Meta parts and store them inside `parts` table in the database. Each part has bytecode value and the tag stored in the table. In order to lookup for the similar contracts, we retrieve all potential parts which are 'Main' and are prefixes of the given remote (supplied by a user) bytecode using sql query. Eventually, for each candidate we try to build the full bytecode value, ignoring 'Meta' parts and check if we succeed.

In the code, the corresponding sql query is located at https://github.com/blockscout/blockscout-rs/blob/main/eth-bytecode-db/eth-bytecode-db/src/search/matches.rs#L114-L125. 

You may also notice, that we do not use the whole main part to be a prefix in the lookup, but only first 150 symbols (or 75 bytes) are used. That was empirically derived number of bytes, enough to have only a small portion of potential candidates found. We have an index created on those 150 symbols (https://github.com/blockscout/blockscout-rs/blob/main/eth-bytecode-db/eth-bytecode-db/migration/src/m20230531_191321_update_parts_data_text_prefix_index_to_150_chars.rs#L11), improve the performance of the query. Also, notice, that we make a search on the `varchar` value, because it is faster than making the same prefix search on `bytea`.

The build of candidates whole bytecode occurs at https://github.com/blockscout/blockscout-rs/blob/main/eth-bytecode-db/eth-bytecode-db/src/search/matches.rs#L72, and we filter them at https://github.com/blockscout/blockscout-rs/blob/main/eth-bytecode-db/eth-bytecode-db/src/search/candidates.rs#L29

**Comment by rimrakhimov** [comment]
For your case though, I'm interested if you need the partial matches to be found at all? As you already have a source code from the user which potentially may be an exact match, you would have to compile those sources anyway, wouldn't you?

**Comment by marcocastignoli** [comment]
I had a nice conversation with @rimrakhimov, the outcome is the following: 

- Even if we search for similar contracts and we find partial matches, we cannot skip compilation because the provided `metadata.json` could result in a perfect match, so we still want to recompile to check if it results in a perfect match.
- So the only way in which we can actually skip compilation is if the searched-bytecode results in a perfect match; in this case is sufficient to search for already existing metadata hashes in the database (we can use the new field we want to add with #1659), we don't need to implement an advanced similarity search. After we found the contracts with the same metadata hash, we apply the transformations like explained above (we still need this step because the verifying-onchain-bytecode could have a fake appended metadata hash):

  > "Do we need to find the transformations applied and 'reverse-transform' them?" My idea is to:
  >  1. use the verifying-onchain-bytecode **'s auxdata hash** to search for all similar bytecodes
  >  2. for each one of them find their transformations in the verified_contracts table (joining with compiled_contracts)
  >  3. apply each transformation to the verifying-onchain-bytecode until we find an exact match with one of the similar bytecodes

**Comment by kuzdogan** [comment]
@rimrakhimov thanks a lot for the insights!

@marcocastignoli for your second point, I get that:
1. we take the on-chain runtime bytecode's metadata hash. We compare it against all of the metadata hashes we've ever seen. We try to find a match
2. If we find a match, we try all existing rows in the `verified_contracts` and re-apply the transformations to see if there's an exact match.

However I think we don't need to limit ourselves to the transformations we already know in the 2nd step. I think we can somehow compare the two runtime bytecodes **except the transformed bytes**. I mean the parts that are supposed to be libraries, immutables etc. Then, if the two bytecodes match except these fields, it's safe to assume the same fields are transformations in the onchain bytecode too. 

In your case we only limit ourselves to the transformation *values* we've ever seen. Say if a contract was initiated with an immutable value of `0x00..abcd`. If the new onchain bytecode has `0x00..abcd` all good because that transformation is found in our DB. But if it was `0x00..1234` we wouldn't be able to verify this because that value was not found in our transformations. It should still be possible to verify with a transformation value we haven't seen before.

**Comment by marcocastignoli** [comment]
> It should still be possible to verify with a transformation value we haven't seen before.

I understand you point, I just have a doubt: couldn't this lead to tailored made bytecodes to take advantage of us not checking specific parts of the bytecode?

In other words, if an attacker knows we’re skipping verification for specific parts of the bytecode (our db is public), they could craft bytecodes that appear valid but contain malicious logic in the sections not replaced by transformations. I don't know if I'm just being too paranoid :)

**Comment by rimrakhimov** [comment]
Thanks, @marcocastignoli for perfectly summarizing what we've discussed :)

I just wanted to add that it seems it may not be possible to find contracts which do not have metadata hashes at all (e.g., compiled with `"metadata.appendCBOR": false` option) that way, even though their recompilation will never get you the perfect match. Not sure, if you would be okay with those cases.

Likewise, I also believe that @kuzdogan suggestion should not break anything because isn't that just the same thing you guys do when comparing just compiled sources with a remote bytecode in a usual verification pipeline?

**Comment by marcocastignoli** [comment]
> Likewise, I also believe that @kuzdogan suggestion should not break anything because isn't that just the same thing you guys do when comparing just compiled sources with a remote bytecode in a usual verification pipeline?

I don't think so. In our usual verification pipeline we first apply the transformation, then we compare the bytecodes. What Kaan is suggesting above is to consider two bytecodes equal even if we don't have the transformation for a differing parts of bytecode: assuming that those parts are libraries.

**Comment by marcocastignoli** [comment]
I didn't get what Kaan was saying above. So just to recap the process:

1. We take the on-chain runtime bytecode's metadata hash. We compare it against all of the metadata hashes we've ever seen. We try to find matches
2. We compare the runtime bytecodes, ignoring the sections that are subject to transformations. If the remaining parts of the bytecodes match, we can safely assume that the differing sections correspond to the same transformations in the on-chain bytecode as well.

I'm closing this discussion, we'll keep track of the implementation in a separate issue.
