### ISSUE TITLE
Improve ui

### ISSUE THREAD

**Issue by edisinovcic** [ethereum/sourcify#167]
Ideal flow:
entering an address: without having to press a "submit"-button, the server automatically triggers a verification of those addresses on all chains. If there is a match, that is reported to the user. If the metadata file is retrievable via ipfs, the user is notified about which other files are missing
selecting a file / multiple files: check if it is a metadatA file, send it to the server, server tries to fetch all mentioned files via ipfs and reports to the user what is missing
User interface supplies the missing files
and it should also work if I select multiple metadata files - then the server should try to verify all of them.
Actually that can be driven from the UI: The UI can search the metadata for the source links, check if it has the files or ask the server if they are retrievable via ipfs.

**Comment by edisinovcic** [comment]
@chriseth correct if something is wrong here.

**Comment by edisinovcic** [comment]
Metadata parses and fetcher can be published on npm as a package so it can be used on both frontend (ui) and backend server.

**Comment by edisinovcic** [comment]
Update react-dropzone on ui to be append only (do not reset file state after new files have been added).

**Comment by chriseth** [comment]
Sounds good! When we just send a metadata file to the server, the server should first check if it corresponds to a deployed contract (we might need the address for that). Otherwise this could be abused to request arbitrary files via ipfs. If the metadata is verified to correspond to a deployed contract, we should always consider source files sent together with the metadata file and also try to fetch them from ipfs in parallel.

The main reason for also trying to fetch them from ipfs: Many contracts out there consist of big contract systems where we have e.g. 20 source files and compile 5 contracts out of them and most of the source files are shared. After having verified the first contract, the others might not need the source code anymore because it is already on the server and thus on ipfs.

**Comment by edisinovcic** [comment]
Validation should also cover: 
https://github.com/ethereum/source-verify/issues/166
https://github.com/ethereum/source-verify/issues/165
