### ISSUE TITLE
repo: remove requirement for tailing slash

### ISSUE THREAD

**Issue by ligi** [ethereum/sourcify#226]
Currently: https://contractrepo.komputing.org/contracts/partial_match/1/0x35D1b3F3D7966A1DFe207aa4514C12a259A0492B

results in an 404 but 

https://contractrepo.komputing.org/contracts/partial_match/1/0x35D1b3F3D7966A1DFe207aa4514C12a259A0492B/

resolves.

ideally the link also resolves without the slash. I guess this is just some configuration in nginx

**Comment by edisinovcic** [comment]
This is definitely a good first issue for those who have played with https://larsjung.de/h5ai/.

Anyone with basic PHP or/and apache skills could help with this.

**Comment by Jakic007** [comment]
I don't think this is an issue anymore.
It only happens when the directory does not actually exist in the repository like the one in the first comment.
For example, if you try with these links, it resolves fine:

https://contractrepo.komputing.org/contracts/partial_match/1/0x6f259637dcD74C767781E37Bc6133cd6A68aa161/
https://contractrepo.komputing.org/contracts/partial_match/1/0x6f259637dcD74C767781E37Bc6133cd6A68aa161
