### ISSUE TITLE
UX: show stats

### ISSUE THREAD

**Issue by Jakic007** [ethereum/sourcify#304]
When this endpoint is added https://github.com/ethereum/sourcify/issues/303 use it to display some stats on the webpage.

**Comment by ligi** [comment]
I think it could make sense to not just display numbers but plotted the graph over time. Reasoning:
 * our numbers are quite low in the beginning - but if we have graphs showing progress could be more inviting
 * graphs look nicer than plain numbers
 * we could see patterns (spikes (so we might also see if endeavors like stateofdapps are useful), flatlines (maybe due to bugs), ..)
