### ISSUE TITLE
Solidity 0.8.x - [BREAKING] do not serialize fields abi, devdoc, userdoc and storage-layout

### ISSUE THREAD

**Issue by edisinovcic** [ethereum/sourcify#326]
Issue discribed here: https://github.com/ethereum/solidity/pull/10409

Add special handling for version 0.8 onwards.

**Comment by FabijanC** [comment]
After inspecting the solc breaking changes and testing Sourcify with a solc0.8.0-compiled contract, I have come to the conclusion that the changes do not affect Sourcify. This is because Sourcify depends on using using the standard-json option of solc, whereas the breaking changes affect the combined-json option.
