### ISSUE TITLE
Contract interaction through api works, not shown in repository

### ISSUE THREAD

**Issue by edisinovcic** [ethereum/sourcify#343]
Contract: 0x3c943fb816694d7d1f4c738e3e7823818a88dd6c
Network: Ropsten
There is no sight of this contract in repo but it is available when fetched through Remix sourcify plugin.
Should be available on this link: https://repo.sourcify.dev/contracts/full_match/3/0x3c943fb816694d7d1f4c738e3e7823818a88dd6c/

**Comment by Jakic007** [comment]
Problem here is that the link specified does not have checksummed address. Sourcify preserves the original checksummed address so this contract is available here: https://repo.sourcify.dev/contracts/full_match/3/0x3c943Fb816694d7D1f4C738e3e7823818a88DD6C/
and not here:
https://repo.sourcify.dev/contracts/full_match/3/0x3c943fb816694d7d1f4c738e3e7823818a88dd6c/

Fetching through API works because we are doing conversion to checksummed format for every request.

**Comment by edisinovcic** [comment]
> Problem here is that the link specified does not have checksummed address. Sourcify preserves the original checksummed address so this contract is available here: https://repo.sourcify.dev/contracts/full_match/3/0x3c943Fb816694d7D1f4C738e3e7823818a88DD6C/
> and not here:
> https://repo.sourcify.dev/contracts/full_match/3/0x3c943fb816694d7d1f4c738e3e7823818a88dd6c/
> 
> Fetching through API works because we are doing conversion to checksummed format for every request.
> Since the implementation of the repository is written in php it is not possible to use web3 library to do the same conversion as in the server API.

Ah okay. @yann300

**Comment by yann300** [comment]
oh ok thanks for the clarification, might be that the plugin need an update cause I got the link from it.

**Comment by Jakic007** [comment]
Oh, thanks for noting that. That definitely should be fixed on the plugin side by converting to checksummed format before constructing the URL. 👍 
I will create the issue on the sourcify remix plugin repo.
