### ISSUE TITLE
In Remix with the Sourcify plugin Verifying with imports from github errors

### ISSUE THREAD

**Issue by ryestew** [ethereum/sourcify#366]
Having compiled & deployed this file to rinkeby:
```
pragma solidity >=0.6.0 <0.7.0;

import "https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/access/Ownable.sol";

contract GetPaid is Ownable {
  function withdraw() external onlyOwner {
  }
}
```
and then going to the Sourcify to verify it at this address:
0xE2740A8A084Ec0F5D233ebC20e91aC6F56C376e9

I get this error in the sourcify plugin:

```
"Invalid or missing sources in:\nContext (https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/utils/Context.sol)"
```

(also note the small test error within the error with the \n)

Is there an issue with verifying contracts that import other contracts that in turn import other contracts?

**Comment by FabijanC** [comment]
Sourcify server does everything correctly, the problem is in the files it receives. The plugin does not send the correct files. In your case, the files sent were the metadata.json of the Context contract and the source file of the GetPaid conract.

This is an issue with the plugin; relevant information will be posted to this issue: sourcifyeth/remix-sourcify#50
