### ISSUE TITLE
Investigate possible integrations with useDapp

### ISSUE THREAD

**Issue by marcocastignoli** [ethereum/sourcify#759]
_useDapp is a framework for rapid Dapp development for React that makes available lots of React hooks to make dApp development easier_

While I was attending useDapp's talk at EthPrague I thought about creating a npx action that automatically gets the abi from the bytecode and creates all the useXXX through this api https://usedapp-docs.netlify.app/docs/API%20Reference/Hooks#usecall

I think we should start a conversation with them, they seem open to new ideas like this one

useDapp links:
* https://discord.gg/cSSmtdq7jr
* https://github.com/TrueFiEng/useDApp

**Comment by rzadp** [comment]
Hello @marcocastignoli 

We are the team working on useDapp - me, @yivlad and @mj426382

I think this idea sounds very interesting, we will do our best to help you make this happen.

**Comment by rzadp** [comment]
@marcocastignoli My understanding is that the first step of the pipeline (once you have the ABI one way or the other), would be to use [TypeChain](https://github.com/dethcrypto/TypeChain) to generate typed code based on Ethers Contracts.

**Comment by marcocastignoli** [comment]
ok, just to recap:
1. from the bytecode of a smart contract: get the Metadata File from IPFS 
2. pass the metadata.output (contains abi+docs) to typechain
3. create the useX API using the generated factory

Do @rzadp , @yivlad, @mj426382 you have suggestions about how to do point 3. ?

**Comment by yivlad** [comment]
@marcocastignoli a separate package with the CLI in the [useDApp](https://github.com/TrueFiEng/useDApp) monorepo sounds like a sensible solution to me. I think in the most basic scenario the CLI should contain the following options:
1. Build directory with the typechain files.
2. Name of the contract (we can then find the appropriate file).
3. Name of the method in the contract to generate hook for (generate for all methods if omitted). 
4. The output directory to store generated hooks.

**Comment by marcocastignoli** [comment]
How do you handle overloading methods?

**Comment by yivlad** [comment]
I think in case of overloading methods when using hooks you have to specify which method exactly you want to use:
```ts
useCall({
    contract: sumContract,
    method: 'getSum(uint256,uint256)',
    args: [2, 2]
  })
 useCall({
    contract: sumContract,
    method: 'getSum(uint256,uint256,uint256)',
    args: [2, 2, 2]
  })
```

**Comment by kuzdogan** [comment]
I see @marcocastignoli and @yivlad are approaching from different sides but I don't see them as mutually exclusive.

1) The very first thing needed for calling methods and possibly creating use<Method> hooks is the ABI of the contract. From what I understood, useDapp currently assumes the ABI JSON file to be present in the source code. In this case, the only thing to do is to generate the wrapper hooks via the existing ABI.

2) The path @marcocastignoli suggests is to dynamically fetch the ABI of a contract from its bytecode. TLDR; Smart contracts usually have an IPFS hash of the metadata file appended to the bytecode. The metadata file contains ABI, Natspec, and compilation settings. Fetching this file via its IPFS hash and using the ABI, one can dynamically generate use<Method> hooks, given a contract address if the metadata is available on IPFS. (You can see this in [the playground](https://playground.sourcify.dev) in action). 

While the first one is simply adding wrappers with the existing `useCall` hook, the second would require passing a Web3 provider, getting the bytecode, fetching over an ipfs gateway, and decoding. I'd imagine the latter comes in handy when building a general-purpose contract interaction UI: pass the contract address and we'll build the frontend for you. Otherwise, I couldn't see how to make use of Sourcify or dynamically fetching ABIs. We can safely assume a dApp developer already has ABIs at hand. Maybe @marcocastignoli has another use case.

**Comment by marcocastignoli** [comment]
@kuzdogan I believe that having one CLI that given an ABI, it outputs the useX methods is something needed by everyone.

We can then extend the functionality of that CLI passing an address and extracting the ABI from the bytecodes instead of the abi files.

**Comment by marcocastignoli** [comment]
By the way I implemented an integration between useDapp and Typechain, [here](https://github.com/0xHabitat/0xhabitat-devenv/blob/main/pages/index.tsx) you can see an example. I'm not using a CLI yet (it's the next step), right now it generates the useDapp hooks/methods live.

Depending on the stateMutability of the function:
- for view: useCall
- for write: useContractFunction

The library is this one: https://github.com/0xHabitat/0xhabitat-devenv/blob/2e8ee33cd9442360423be2b8036aa572c124e3b0/utils/generateUseDiamond.ts

(@kuzdogan I'm generating the typechain factories from the metadata in the bytecode)
