### ISSUE TITLE
Feature: sharable links for playground.sourcify

### ISSUE THREAD

**Issue by hrkrshnn** [ethereum/sourcify#772]
Really love https://playground.sourcify.dev/

It would be nice to have something like https://playground.sourcify.dev/address/0x1234.... that would open up the playground for the specific address. Useful for sharing.

**Comment by kuzdogan** [comment]
Hey Hari thanks! 

It was actually there but you had to pass `address` and `chainId` both and was not documented. Fixed with https://github.com/sourcifyeth/metadata-playground/commit/53b22b270f3e3ec44e18da9efc1e4c6e2d2ac4f4 

Params can be passed with <https://playground.sourcify.dev/?address=0xb36c99e9a86ff467bbf4312ae852874f7a6fe57d&chainId=69>

**Comment by hrkrshnn** [comment]
Amazing! Thanks
