### ISSUE TITLE
Fix Tests

### ISSUE THREAD

**Issue by kuzdogan** [ethereum/sourcify#803]
Adding this as an issue to keep track. 

It seems two types tests are failing randomly. The most common error is `ENOENT: no such file or directory, open 'mockRepository6769977007804346/contracts/full_match/0/0x4e3766fD706442405C739ba07ed28bc09A9Fec7e/metadata.json` [Example](https://app.circleci.com/pipelines/github/ethereum/sourcify/3084/workflows/5746836b-6e85-4a2c-864a-4506fd10de36/jobs/16250)

The other one I noticed is with ipfs and can be seen [here](https://app.circleci.com/pipelines/github/ethereum/sourcify/3084/workflows/43c9514e-2cf2-4a4a-b2c4-6f028b5b20fb/jobs/16235)
```
ethereum-sourcify:       1) should fetch a missing file that is accessible via ipfs
ethereum-sourcify: Server response of failed test should fetch a missing file that is accessible via ipfs:
ethereum-sourcify: {
ethereum-sourcify:   error: 'Resource missing; unsuccessful fetching: project:/contracts/Storage.sol'
ethereum-sourcify: }
```

It might be normal for the second one to fail occasionally if the network requests are failing or the IPFS GW can't find the file. 

- [x] Fix `mockRepository` tests
- [ ] Fix `should fetch a missing file that is accessible via ipfs`

**Comment by marcocastignoli** [comment]
> Fix mockRepository tests

It seems like it's no more related to async/await issues (it was definitely, but it continued failing after my fix). The only problem remaining is that the `MONITOR_SECS=25` sometimes is not enough.
I believe it's cleaner to avoid waiting a random number of seconds but listen for events coming from the Monitor.

I extended the Monitor with EventEmitter, and I'm emitting two events:
* contract-verified-successfully
* contract-already-verified

I listen for these two events in the tests instead of waiting for `MONITOR_SEC`.
Now tests are faster and hopefully working all the times.

**Comment by marcocastignoli** [comment]
About IPFS I would try to change the default gateway and use something more stable than ipfs.io
Personally I think cloudflare-ipfs.com is the best. I also found [this nice comparison](https://www.reddit.com/r/ipfs/comments/lvwn4o/ipfs_http_gateways_ranked_by_performance/) on reddit
