### ISSUE TITLE
Update Metadata Playground 

### ISSUE THREAD

**Issue by kuzdogan** [ethereum/sourcify#841]
- [ ] Update the Metadata Playground to use the `@ethereum-sourcify/bytecode-utils` once the package is published on npm
- [x] Move Sepolia up in the list after Goerli. Currently it is too low because of its chainId
- [x] Use a working Sepolia RPC. The first one doesn't seem to be working and when Sepolia is selected it is stuck in "Loading"

**Comment by marcocastignoli** [comment]
While looking at this, I realized that the `bytecode-utils` package is not returning the raw cbor information. I think that this is a potential improvement. I'm experimenting a new return type of the `decode` method instead of the [current implementation](https://github.com/ethereum/sourcify/blob/staging/packages/bytecode-utils/src/lib/bytecode.ts#L11-L15):

```ts
type DecodedObject = {
  raw: {
    ipfs?: string;
    bzzr0?: string;
    bzzr1?: string;
    solc?: string;
    [key: string]: string | Uint8Array | undefined | boolean;
  };
  decoded: {
    ipfs?: string;
    bzzr0?: string;
    bzzr1?: string;
    solc?: string;
    [key: string]: string | Uint8Array | undefined | boolean;
  };
  metadataOrigin?: 'ipfs' | 'bzzr0' | 'bzzr1';
};
```

@kuzdogan what do you think? If you think it's a good idea, I'll open an issue to track this specifically.

**Comment by kuzdogan** [comment]
Yes it could be nice to have it.

I also think we should refrain from using generic types and be explicit, i.e. add `experimental` here. There are only so many fields in the CBOR data: https://docs.soliditylang.org/en/latest/metadata.html#encoding-of-the-metadata-hash-in-the-bytecode
