### ISSUE TITLE
[ui]: Give repo link on create2 lookup results

### ISSUE THREAD

**Issue by kuzdogan** [ethereum/sourcify#869]
The lookup results of create2 contracts currently does not include a link to the repo. Add a link to the repo as in other results

<img width="980" alt="image" src="https://user-images.githubusercontent.com/13069972/207086676-78af0872-12ed-4b83-acc8-79c3b72ac7bb.png">

**Comment by uday03meh** [comment]
Hi,
Can someone please assign this to me?

**Comment by kuzdogan** [comment]
Sure, there you go!

**Comment by Uttam-Singhh** [comment]
Hey @kuzdogan,
I would love to contribute here, I have few questions:

- * According to the above img the contract is verified but how can you verify a contract before it is deployed?
-* And when you say - ink to the repo you mean the button that says View in Sourcify Repository!

**Comment by marcocastignoli** [comment]
Hey @Uttam-Singhh, I love to see you here! Basically each chain in stored in the repo with its own chainId. (e.g. /contracts/full_match/CHAIN_ID/ADDRESS), create2 contracts are an exception because they are potentially not deployed on any chain (you can read more here: https://docs.sourcify.dev/docs/create2/). In the image you posted above the UI is telling you that the contract is in the repo in both _/contracts/full_match/0/0x3957..._ and _/contracts/full_match/1/0x3957..._, but only the link to _/contracts/full_match/1/0x3957..._ is accessible via the link you mentioned above. We need a second link next to the create2 information

**Comment by marcocastignoli** [comment]
@Uttam-Singhh hey! Do you have any updates regarding this? If not I will take this task
