### ISSUE TITLE
In CheckedContract's constuctor updating the sources content works diffrently from before the refactoring

### ISSUE THREAD

**Issue by marcocastignoli** [ethereum/sourcify#902]
check the referenced comment below

<sub>View in Huly <a href="https://app.huly.io/guest/w-kaanuzdogan-sourcify-65d30de0-75121c5c6c-fd615e?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NWU1N2ViYThiNmVjZDA0ZDYyZDJkNzIiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6Incta2FhbnV6ZG9nYW4tc291cmNpZnktNjVkMzBkZTAtNzUxMjFjNWM2Yy1mZDYxNWUiLCJwcm9kdWN0SWQiOiIifQ.NUcCJv5m8tq05CZM7Oqyq_abLJSCV7b5Ci4Vhwwy3iA">HI-486</a></sub>

**Comment by kuzdogan** [comment]
TODO: Summarize the issue in detail

This might be fixed but might have affected older contracts. We need to check the whole repo

**Comment by marcocastignoli** [comment]
There used to be a loop in the CheckedContract constructor that was mistakenly rewriting the metadata.

https://github.com/ethereum/sourcify/blob/bd67c955f34698c9b6bc16d9754d933d8afc2a0f/packages/lib-sourcify/src/lib/CheckedContract.ts#L82-L91

The variable `sources`is a reference to the metadata's sources. This means that potentially some saved metadata in the repo contains content and no license fields

**Comment by kuzdogan** [comment]
This will not cause a problem if we recompile the contract with the existing incorrect metadata (that's missing the `license` field) it will output the correct metadata without problems because the license field does not affect compilation. We just need to save the output metadata when we are doing a recompilation.

The problem this causes is that the correct metadata does not get pinned on IPFS

**Comment by kuzdogan** [comment]
I guess this can be closed?

**Comment by marcocastignoli** [comment]
We solved this by re-verfifying all the contracts #1287 

I also mentioned this issue in the docs
