### ISSUE TITLE
Check if it is possible to fully verify contracts by "deflattening"

### ISSUE THREAD

**Issue by kuzdogan** [ethereum/sourcify#999]
A common way people verify contracts on Etherscan is by "flattening" them i.e. merging all the contract source code in a single file and verifying. This completely breaks the metadata hash match as originally the files were provided individually to the compiler.

This leaves me thinking if we can **deflatten** the contracts to be able to get a full match. If we can find some cases where this is possible and it's generalizable we can add this to our `tryToFindFullMatch` pipeline when we get a partial match.

**Comment by sealer3** [comment]
The [Truffle flattener](https://github.com/NomicFoundation/truffle-flattener) is one of the first and (I think) predates the Remix plugin. It seems like the [Remix plugin](https://github.com/bunsenstraat/flattener) is based from this one but was converted to TypeScript.

The code lives on as a built-in feature of Remix (in the context menu of a source file), with setup code in the [frontend](https://github.com/ethereum/remix-project/blob/master/apps/remix-ide/src/app/plugins/contractFlattener.tsx) and the code parsing in the [backend](https://github.com/ethereum/remix-project/blob/master/libs/remix-ui/solidity-compiler/src/lib/logic/flattenerUtilities.ts). I have seen it used in many verified contracts.

Unfortunately, this flattener is destructive, [getting rid of all the lines](https://github.com/ethereum/remix-project/blob/21710a430f6b92d861b4e5025a2897a1b55d9a5c/libs/remix-ui/solidity-compiler/src/lib/logic/flattenerUtilities.ts#L16) that contain imports and SPDX identifiers, which will make things hard because the SPDX identifiers of dependency contracts might be different than the base contract. It does preserve the file names in a comment. `_flattened` is added to the name of the contract on Remix.

Making things complicated is that the compiler is upset if there are multiple SPDX identifier comments in a single file.

Over the next few weeks, I'll see if I can make a program that tries to brute force a perfect match from contracts that use this flattener, starting with some of my own test examples. The idea is to get a better understanding of whether it is possible to get perfect matches at all. If the contracts were compiled unflattened, I expect the difficulty will grow exponentially with the number of files that were flattened and the number of import statements. The difficulty can be reduced by identifying known smart contracts (e.g. OpenZeppelin) and inferring their imports/SPDX identifiers.

We should also look at the order of the files and how the dependency graph is calculated. We might be able to glean some information about the original order of imports. However, some flatteners are (or were) non-deterministic in computing the dependency graph.

Hardhat also [has one](https://github.com/NomicFoundation/hardhat/blob/main/packages/hardhat-core/src/builtin-tasks/flatten.ts) with a similar flavor. The Hardhat and Truffle ones trim whitespace on all imported files, which will make some contracts very hard to reverse perfectly.

There might be other flatteners I have missed, but these are popular ones.

The smartest path to more perfect matches is to change these flatteners to make them invertible for source code verification purposes, to discourage developers from using flatteners for source code verification, and to spread the word with a step-by-step guide about how to upload with full metadata from different development toolkits.

**Comment by kuzdogan** [comment]
Unfortunately we won't be able to prioritize this as this would need a lot of experimentation. 

However we should start fighting against flatteners as a long-term separate goal.

**Comment by sealer3** [comment]
I did write a rather simple script that was able to de-flatten some minimal Remix examples (e.g. ones with a single import). But even for a single import, it has to try about 50 variations (which SPDX identifier?, which empty line actually had an import?, which import was it?). I think it's too many recompiles for being part of a verification pipeline.

In the far future maybe there could be a contest for most partial -> full verifications which could incentivize discovering better heuristics for deflattening, but discouraging flatteners altogether is definitely the way to go.

**Comment by kuzdogan** [comment]
Agree, thanks for the input. 

Just adding this Stackoverflow thread for future ref https://ethereum.stackexchange.com/questions/135433/how-to-un-flatten-a-smart-contract-in-soliditty
